### ISSUE TITLE
Update icon: synology.com

### ISSUE THREAD

**Issue by kongo09** [aegis-icons/aegis-icons#127]
The provided synology icon is not the official icon as represented by the synology.com favicon:

- https://www.synology.com/img/icon/favicon@2x.png

**Comment by krisu5** [comment]
Synology's logo in the icon is based of [Simple Icons](https://simpleicons.org/?q=syno) version. It's compromise for space usage. Favicon uses same typeface as the logo's first part.

Logo and color is otherwise correct and needs no updates.

https://www.synology.com/en-global/company/branding

**Comment by ukanuk** [comment]
The current logo in your SimpleIcons link and in the official brand guidelines you link all use the full word "Synology", they never abbreviate to just Syno. The current logo in this repo just uses the abbreviation "Syno". Did it used to be just Syno and has been recently changed, or did you choose to abbreviate it to just Syno? 

Regardless, would you consider adding a variant with the full logo? Imo since there are already logos with long words like Samsung, Shareworks, Bethesda, etc., it's more consistent to use the full "Synology" than the abbreviated "Syno".

**Comment by krisu5** [comment]
> The current logo in your SimpleIcons link and in the official brand guidelines you link all use the full word "Synology", they never abbreviate to just Syno. The current logo in this repo just uses the abbreviation "Syno". Did it used to be just Syno and has been recently changed, or did you choose to abbreviate it to just Syno?

It was like that before in Simple Icons, it seems to been updated. https://github.com/simple-icons/simple-icons/pull/4220

I'll reopen this one.

**Comment by krisu5** [comment]
Fixed.

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Synology.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Synology.svg
