### ISSUE TITLE
Update icon: Microsoft v2

### ISSUE THREAD

**Issue by fiorins** [aegis-icons/aegis-icons#140]
- URL of the site or app **(required):**  microsoft.com
<img width="370" alt="Screenshot 2020-11-29 at 16 06 32" src="https://user-images.githubusercontent.com/32281481/100549630-58a90880-3274-11eb-91e6-27bc38be42f1.png">

hello can you also a version of microsoft icon with colours ? I'll be grateful to you

- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Microsoft icon was recently updated and color is taken from logo's text, because that's most neutral choice. I'm not making icon based of Microsoft's four colors.

[You can make own version if you want.](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#how-can-i-make-icon-with-different-background-color)
