### ISSUE TITLE
Icon request: Mercadolivre

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#151]
- URL of the site or app **(required):** https://www.mercadolivre.com.br/
- Logo resources for the icon **(optional, but recommended):** https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6eALnrl52w1tk50w8hXDVAAAAA%26pid%3DApi&f=1

**Comment by krisu5** [comment]
So, is the current "elbow to elbow" logo just corona PR stunt, that's just temporary? Based of what I found out with Google translation: https://newgrowing.com/mercado-livre-atualiza-logotipo-em-acao-de-incentivo-a-prevencao-ao-coronavirus/

Confirming just in case.

SVG Vector for handshake logo: https://en.wikipedia.org/wiki/File:MercadoLibre.svg

**Comment by ghost** [comment]
Didn't even notice that they changed their logo. I read that its a temporary change.

**Comment by krisu5** [comment]
I gone with handshake logo then :)

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/MercadoLibre.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/MercadoLibre%20fg.var.png

(I named it with spanish name, because it seems more common and Wikipedia article uses that name too).
