### ISSUE TITLE
Icon submission: Shareworks

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#179]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.shareworks.com/
- Logo resources for the icon:
  - [SVG logo on homepage](https://www.shareworks.com/wp-content/uploads/2020/05/shareworks-by-morgan-stanley-north-america.svg)

Uploaded files:
[Shareworks.zip](https://github.com/aegis-icons/aegis-icons/files/6179128/Shareworks.zip)
![Shareworks](https://user-images.githubusercontent.com/1494739/111934102-0176b000-8a7e-11eb-8a40-39353d0bff46.png)

**Comment by krisu5** [comment]
I had to remake this one, sorry about that. It's my fault really because guidelines doesn't mention this.

If logo is based of really generic sans-serif font (and doesn't have logomark), then I personally don't use first letter of the logo. Because it doesn't differentiate from the Aegis's default letter icon.

**Comment by Selovert** [comment]
That's fine. I'll mention that the "S" is used by their app, so it is recognizable to me. The whole title looks good as well, though!

![Screenshot_20210322-063605](https://user-images.githubusercontent.com/1494739/111998529-54318580-8ad9-11eb-9a33-6769af0c0e37.png)
