### ISSUE TITLE
Merge this project into Aegis itself

### ISSUE THREAD

**Issue by hopoluicha** [aegis-icons/aegis-icons#23]
It will be fantastic

**Comment by krisu5** [comment]
Well, there has been [discussion](https://github.com/beemdevelopment/Aegis/issues/63) about how to handle icons in the future.

If icons are embedded into the app, main problem would be maintenance with Aegis dev team. I guess I could do maintenance, if it isn't too technically difficult. But another problem would be delayed icon releases because of possibly irregular app updates.

And hosting outside somewhere and connecting to icon database is out of the question, because they want to keep Aegis offline as much as possible (privacy reasons).

This seems to be non-priority with Aegis dev team right now, but opening issue there instead would change that possibly.

**Comment by hopoluicha** [comment]
alright thanks for the explanation

**Comment by Wilker-uwu** [comment]
in Git, subrepositories can be set into the repository. in practice, that means that cloning the Aegis repo will automatically clone the icons repo together in a subfolder. that will allow Aegis to freely use the files in the icons repo in the code while still keeping the projects separated.
