### ISSUE TITLE
Some icon background blends into the background in amoled theme

### ISSUE THREAD

**Issue by hopoluicha** [aegis-icons/aegis-icons#24]
When I select amoled theme in Aegis, icons with black background blends completely into the theme's background. Actually not sure if this is an issue.

**Comment by krisu5** [comment]
I assume you mean icons with darker / full black background?

Yeah, I knew the issue, but there isn't good way to solve this (at least from my perspective).

One would be adding white border around the icon. But with that solution it's possible that bordered icons look smaller then others.

Second solution would be just changing the color slightly or completely. I have thinked about changing Snapchat's icon BG slightly, because that yellow doesn't work with white at all. So maybe?

**Comment by krisu5** [comment]
There's now color variations for darker themes.
