### ISSUE TITLE
Icon submission: HackerOne

### ISSUE THREAD

**Issue by edent** [aegis-icons/aegis-icons#258]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.hackerone.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://www.hackerone.com/branding

Uploaded files:
[hackerone.zip](https://github.com/aegis-icons/aegis-icons/files/6583645/hackerone.zip)

I think I've done this right. The file is from my https://github.com/edent/SuperTinyIcons/ project. If this fits the requirements, I can upload the rest of them where appropriate.

**Comment by krisu5** [comment]
Wrong file? There's no circle in that SVG in uploaded ZIP.

Suggestions for icon:
- Logo centered, height would be from top and bottom of guides
- Make icon with `#000000` background color
- Make `bg.var` variation icon with `#e41473` background color (taken from website design)

EDIT: okay, now I understand what you mean. I misunderstood earlier.

Sorry, but we cannot accept this and other SuperTinyIcons icons **as is** here, because of these design guidelines:

1. Logo must be on the circle provided by the template files
2. Background cannot be white, white is for logo only
3. All the logos has to monochrome (meaning only one color, no transparency etc)

I've known your project for sometime and I appreciate it, but we here are more focused on design consistency then file size effency.

**Comment by krisu5** [comment]
I'm gonna close this in two weeks, if there's no further updates.
