### ISSUE TITLE
Generic icon request: Education

### ISSUE THREAD

**Issue by bannurowi** [aegis-icons/aegis-icons#267]
A generic education icon for various school/university/other similar websites could be useful. Maybe using graduation-cap (e905) or book-open (eb17) from [Unicons](https://iconscout.com/unicons/explore/line)?

Edit: https://2fa.directory/ uses something closer to book-alt (e8fe) for their Education category, for what it's worth.

**Comment by krisu5** [comment]
I picked graduation gap, because it's most visually distinct.

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Generic/Education.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Generic/Education.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
