### ISSUE TITLE
Icon submission: Forum Italia

### ISSUE THREAD

**Issue by matteoballabio** [aegis-icons/aegis-icons#283]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://forum.italia.it/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://github.com/italia/developers.italia.it/blob/master/assets/icons/logo-it-blue.svg
- Icon source: https://github.com/italia/developers.italia.it/blob/master/assets/icons/logo-it.svg

Uploaded files: [Forum Italia.zip](https://github.com/aegis-icons/aegis-icons/files/6755900/Forum.Italia.zip)

**Comment by krisu5** [comment]
Added to the repo.

**EDIT 2022-02-24:** icon removed because of new ["icon acceptability criteria"](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis), the removed SVG can be found from here: https://github.com/aegis-icons/misc/blob/main/removed_icons/Forum%20Italia.svg
