### ISSUE TITLE
Icon request: Star Wars: The Old Republic

### ISSUE THREAD

**Issue by csamolot** [aegis-icons/aegis-icons#295]
- URL of the site or app **(required):** https://www.swtor.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Compromise with the logo, since there's no vector for official SWTOR logo and raster images are too complex for image tracing.

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Star%20Wars%20The%20Old%20Republic.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Star%20Wars%20The%20Old%20Republic.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
