### ISSUE TITLE
Icon request: Allegro.pl

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#325]
URL of the site or app (required): https://allegro.pl/
Logo resources for the icon (optional, but recommended):

**Comment by ghost** [comment]
By the way I made [Concept](https://github.com/aegis-icons/aegis-icons/files/7032128/Allegro.pl.gz) of this icon in free time

**Comment by krisu5** [comment]
Biggest issue with your icon is **drop shadows**. Android's SVG feature doesn't support drop shadows at all and our guidelines forbids using those, because we want everything to be "flat". Vector graphics and drop shadows in general are bad idea. Also these drop shadows viewed at browser look way off.

Other issues
- Canvas isn't 1024 x 1024px 
- Logo uses gradient colors
- Logo is taken from app icon and therefore incorrect (this is the correct one, on the website: https://i.imgur.com/GwY0dqg.png)

Anyways, here's the icon:
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Allegro.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
