### ISSUE TITLE
Icon request: Minds

### ISSUE THREAD

**Issue by d4f5409d** [aegis-icons/aegis-icons#330]
- URL of the site or app **(required):** https://minds.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Rejected because of [guideline 5b](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines), example: https://en.wikipedia.org/wiki/Minds#Deradicalization

**Comment by krisu5** [comment]
After lot of research, I have decided to reject this issue because of [issue guideline 5b](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

Minds "tries to be" a good guy, but is totally okay with hate speech on their site in several occasion. I'm not comfortable with making icon for this site.

Sources:
https://en.wikipedia.org/wiki/Minds#Content
https://www.vice.com/en/article/wjvp8y/minds-the-anti-facebook-has-no-idea-what-to-do-about-all-the-neo-nazis

**Comment by krisu5** [comment]
It doesn't matter if it's icons or something else, it's my project that I do in my free time and put 100s hours already. My project, my rules.

And my **only objection** _(at least app / site related)_ for creating icons is knowingly badly moderated / not monitored sites that are filled with fringe groups (alt-right, MAGAs, nazis, you name it). I even looked the site's content to make it sure.

You can always make icon yourself if you want to. Aegis lets you add any image to any entry.
