### ISSUE TITLE
Icon request: Shopify

### ISSUE THREAD

**Issue by jayvogt** [aegis-icons/aegis-icons#34]
- URL of the site or app: https://www.shopify.com
- Logo resources for the icon: https://www.shopify.com/brand-assets
- Hex color of the main brand color: #95bf47

ps: Happy to help make icons if you'd like. I've made an SVG myself, but I can't attach it here.

**Comment by krisu5** [comment]
If you mean icons, yeah sure (as long at it uses template downloaded from repo, "ai_icon_template.ait"). I haven't done guidelines or anything like that (yet), only guideline is using template and its guides. Sorry if that sounds confusing. 😅 

Github doesn't like SVGs as attachments for some reason, you need pack the file into ZIP folder in order to upload it.

Anyways, here's the icon: https://github.com/krisu5/aegis-icons/blob/master/PNG/Shopify.png
