### ISSUE TITLE
Icon request: Newgrounds

### ISSUE THREAD

**Issue by Trung0246** [aegis-icons/aegis-icons#341]
- URL of the site or app **(required):** https://www.newgrounds.com
- Logo resources for the icon **(optional, but recommended):** https://www.newgrounds.com/downloads/designassets

However seems like they only have PNG or PSD version (1000px version), not sure if there's a good tool to convert the logo to svg.

**Comment by krisu5** [comment]
> not sure if there's a good tool to convert the logo to svg.

There are couple, that's why I ask high resolution logo images if no vectors are available. But I found a vector for it.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Newgrounds.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
