### ISSUE TITLE
Icon request: AppFolio Property Manager

### ISSUE THREAD

**Issue by ukanuk** [aegis-icons/aegis-icons#64]
- URL of the site or app
  - https://www.appfolio.com
  - This is specifically for Property Manager, as they have other products too which can use same logo but other brand colors, see https://www.appfolioinc.com/products
- Logo resources for the icon **(optional, but recommended):** 
  - https://pa.cdn.appfolio.com/appfolio/favicons/favicon.ico
  - http://www.appfolio.com/images/html/apm-fb-logo.png
  - http://www.appfolio.com/images/html/apm-logo.png

**Comment by krisu5** [comment]
https://github.com/krisu5/aegis-icons/blob/master/PNG/AppFolio.png

**Comment by ukanuk** [comment]
Thank you, this works! I was expecting just the "a" in the circle, but this is fine too!

Just "a" in circle used on their social media pages:
* https://www.youtube.com/user/appfolio
* https://twitter.com/appfolio
* https://www.linkedin.com/company/appfolio-inc/
* https://www.facebook.com/AppFolio/
* https://play.google.com/store/apps/dev?id=6409979379413406734

![image](https://user-images.githubusercontent.com/59303202/79874351-32400680-8423-11ea-896b-0f5bdd84ec4d.png)

**Comment by ukanuk** [comment]
This is the second time this has happened where I requested an icon, you so kindly and graciously created one for me, and it didn't match my initial expectations (first time was YNAB #36) . Maybe modifying the "Icon request" issue template to include a screenshot of the expected icon would reduce occurrence of this? You're always so generous and speedy making them, and I feel even mentioning an idea for an alternate version.

**Comment by krisu5** [comment]
I'm sorry about that. Thanks for being so nice though :D

I should make a submission guideline or something like that, I put that to the todo list. YNAB was bit different case though, because brand kit only had PNGs (I can't use PNGs, those aren't vector files), so I ignored it and didn't notice that there was a logomark (explaining what that is later in the comment). Logomark vector was thankfully found as hidden in the HTML as Safari pinned icon.

It's kinda hard to explain my process, but I almost always go with the actual logo as main one.

If brand guidelines has clear logomark (it means icon-like symbol, that hasn't any text, kinda like that "a"), then I will make that as alternative. In this case, there's no guidelines or any brand related resources, so I go full logo instead, because it looks like part of the full logo.

Maybe I should always make logomark alternative even if guidelines don't have that, but I fear that would have to make one every single time. This project involved into bit of mess, because I didn't expect this to be even this popular.

But since you ask for, I can make alternative this time too.

**Comment by krisu5** [comment]
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/AppFolio%20alt.png

Is this okay?

**Comment by ukanuk** [comment]
Thank you, that looks great!

> Maybe I should always make logomark alternative even if guidelines don't have that, but I fear that would have to make one every single time. This project involved into bit of mess, because I didn't expect this to be even this popular. 

If you had a CONTRIBUTING.md with SVG creation guidelines, maybe that could help reduce your workload? The biggest value of this project in my opinion is that it's a centralized repository of vector-based stylistically uniform icons which fit straight into Aegis. The fact that you create new ones is super generous, but even if you didn't I would still make my own icons and be happy to submit them to this repo.

If you like, I could try drafting up some sample guidelines to see what you think. My idea is basically a walkthrough tutorial of tips for searching for svg brand images, and how to modify them with Inkscape to match style guidelines of this repo. And I think I'd create a `template.svg` file for people to start from.

**Comment by krisu5** [comment]
> If you had a CONTRIBUTING.md with SVG creation guidelines, maybe that could help reduce your workload? The biggest value of this project in my opinion is that it's a centralized repository of vector-based stylistically uniform icons which fit straight into Aegis. The fact that you create new ones is super generous, but even if you didn't I would still make my own icons and be happy to submit them to this repo.

There's templates for Illustrator, "ai_icon_template.ait" & "ai_icon_template_generic.ait". Of course, these won't work universally everywhere (like Inkscape).

> If you like, I could try drafting up some sample guidelines to see what you think. My idea is basically a walkthrough tutorial of tips for searching for svg brand images, and how to modify them with Inkscape to match style guidelines of this repo. And I think I'd create a template.svg file for people to start from.

Sure, I have also think about making tutorial how to find SVGs like in the websites.

I also need decide on more consistent icon creating guideline, it maybe was a mistake to use just logomarks as secondary option. IDK.

(Closing issue because request was filled).
