### ISSUE TITLE
Icon request: RainLoop Webmail

### ISSUE THREAD

**Issue by columndeeply** [aegis-icons/aegis-icons#705]
### URL for the brand / site / app

https://www.rainloop.net/

### Anything else?

Their [demo page](https://mail.rainloop.net/) seems to be down but they mention 2FA on the security section [here](https://www.rainloop.net/features/). I'm using it on my VPS and it works fine with Aegis.

Couldn't find a SVG of the icon, the one in their repo is a PNG file: https://github.com/RainLoop/rainloop-webmail/blob/master/assets/css/images/rainloop-logo.png

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Good enough SVG logo recreation: https://cdn.franzinfra.com/recipes/dist/rainloop/src/icon.svg

**Comment by columndeeply** [comment]
Gave it a shot with your SVG. It's my first time working with vectors and inkscape so let me know if I messed up somewhere (or if I should use some other colors). If this one is good enough I'll open a PR

![rainloop_compressed](https://user-images.githubusercontent.com/106948293/195998981-3eda1e8b-03d1-4ef3-9cfd-1aa15fb062e0.svg)

**Comment by krisu5** [comment]
Otherwise good for PR, just few things:

1. Logo is slightly too big IMO for this case, scale it inside of the inner guides
2. I don't know where you got that purple BG color? Based of guidelines, color should come from logo first (in this case it's `#000000`) and because of the black BG color, you'll also need bg.var icon with e.g. color of the [site](https://www.rainloop.net/)'s footer (`#323947`, it's light enough for dark / EMOLED themes, I checked).
3. [Remember to do the SVG code cleanup and correct formatting](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup)

**Comment by columndeeply** [comment]
Thanks for the feedback! The purple color is from one of the their themes, it's the one I'm using currently. I misunderstood and thought it was any color used on their software, not just the logo. I'll change it to black and add a bg.var grey version.
![20221016_081116](https://user-images.githubusercontent.com/106948293/196021122-18207516-03cf-448d-9d7e-8435fbd256f5.png)

I'll make a PR with these changes.
