### ISSUE TITLE
Icon request: Signal Community Icon for Aegis 2FA

### ISSUE THREAD

**Issue by EdelStark** [aegis-icons/aegis-icons#94]
• Icon - Signal Community Forum Icon
 • URL - https://community.signalusers.org/

**Comment by krisu5** [comment]
For forums I have decided to make icons based of forum software they use, because those are more universally usable then icons for specific communities. This is judged by case by case.

Signal is also messaging app, so I don't want to confuse people.

Forums are powered by Discourse. Use Discourse icons or generic Talk icon.

https://github.com/krisu5/aegis-icons/blob/master/PNG/Discourse.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Discourse%20bg.var.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Discourse%20alt.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Discourse%20alt%20bg.var.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic/Talk.png

**Comment by EdelStark** [comment]
I understand. Sorry I'm new to Github so it's a bit confusing to me when making a request. Thank you for your work.

**Comment by krisu5** [comment]
> I understand. Sorry I'm new to Github so it's a bit confusing to me when making a request. Thank you for your work.

No problem, most of the requests here are from totally brand new accounts. :) And this wasn't mention in the guidelines, so you wouldn't know before hand anyway (adding it ASAP).
