### ISSUE TITLE
Icon request: XenForo

### ISSUE THREAD

**Issue by EdelStark** [aegis-icons/aegis-icons#95]
• ~~PHcorner Community Forum~~ XenForo
 • URL: ~~phcorner.net~~ https://xenforo.com/

**Comment by krisu5** [comment]
For forums I have decided to make icons based of forum software they use, because those are more universally usable then icons for specific communities. This is judged by case by case.

Also icon is bit hard to make, because 1) there's no vector and 2) logo's graphical styling.

Software that this forum use is [XenForo](https://w3techs.com/sites/info/phcorner.net). I make icon for that instead.

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/XenForo.png
